openapi: 3.0.0
info:
  title: Availability Schedules API
  description: API endpoints for managing availability schedules - define when users are available for bookings
  version: 1.0.0

servers:
  - url: https://api.yourapp.com
    description: Production server
  - url: http://localhost:3000
    description: Development server

paths:
  /api/availability-schedules:
    get:
      summary: Get all availability schedules for the authenticated user
      operationId: getAvailabilitySchedules
      tags:
        - Availability Schedules
      security:
        - bearerAuth: []
      parameters:
        - name: isDefault
          in: query
          required: false
          schema:
            type: boolean
          description: Filter by default schedule
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
          description: Maximum number of schedules to return
        - name: offset
          in: query
          required: false
          schema:
            type: integer
            minimum: 0
            default: 0
          description: Number of schedules to skip for pagination
      responses:
        '200':
          description: Availability schedules retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  schedules:
                    type: array
                    items:
                      $ref: '#/components/schemas/AvailabilitySchedule'
                  total:
                    type: integer
                    description: Total number of schedules
                    example: 3
                  limit:
                    type: integer
                    example: 20
                  offset:
                    type: integer
                    example: 0
        '401':
          description: Unauthorized - invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    post:
      summary: Create a new availability schedule
      operationId: createAvailabilitySchedule
      tags:
        - Availability Schedules
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAvailabilityScheduleRequest'
      responses:
        '201':
          description: Availability schedule created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AvailabilitySchedule'
        '400':
          description: Bad request - invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized - invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/availability-schedules/{id}:
    get:
      summary: Get a specific availability schedule by ID
      operationId: getAvailabilityScheduleById
      tags:
        - Availability Schedules
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Availability schedule ID
      responses:
        '200':
          description: Availability schedule retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AvailabilitySchedule'
        '401':
          description: Unauthorized - invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Availability schedule not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    put:
      summary: Update an availability schedule
      operationId: updateAvailabilitySchedule
      tags:
        - Availability Schedules
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Availability schedule ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAvailabilityScheduleRequest'
      responses:
        '200':
          description: Availability schedule updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AvailabilitySchedule'
        '400':
          description: Bad request - invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized - invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Availability schedule not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    delete:
      summary: Delete an availability schedule
      operationId: deleteAvailabilitySchedule
      tags:
        - Availability Schedules
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Availability schedule ID
      responses:
        '200':
          description: Availability schedule deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Availability schedule deleted successfully"
        '401':
          description: Unauthorized - invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Availability schedule not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Conflict - cannot delete default schedule or schedule in use by event types
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/availability-schedules/{id}/duplicate:
    post:
      summary: Duplicate an availability schedule
      operationId: duplicateAvailabilitySchedule
      tags:
        - Availability Schedules
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Availability schedule ID to duplicate
      responses:
        '201':
          description: Availability schedule duplicated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AvailabilitySchedule'
        '401':
          description: Unauthorized - invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Availability schedule not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/availability-schedules/{id}/set-default:
    patch:
      summary: Set an availability schedule as the default
      operationId: setDefaultAvailabilitySchedule
      tags:
        - Availability Schedules
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Availability schedule ID
      responses:
        '200':
          description: Default schedule updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AvailabilitySchedule'
        '401':
          description: Unauthorized - invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Availability schedule not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    CreateAvailabilityScheduleRequest:
      type: object
      properties:
        name:
          type: string
          description: Schedule name
          example: "Working Hours"
          minLength: 1
          maxLength: 100
        isDefault:
          type: boolean
          description: Whether this is the default schedule
          example: false
          default: false
        timezone:
          type: string
          description: IANA timezone identifier
          example: "America/New_York"
        schedule:
          type: array
          description: Weekly availability schedule
          items:
            $ref: '#/components/schemas/DaySchedule'
          minItems: 7
          maxItems: 7
      required:
        - name
        - timezone
        - schedule

    UpdateAvailabilityScheduleRequest:
      type: object
      properties:
        name:
          type: string
          description: Schedule name
          example: "Working Hours"
          minLength: 1
          maxLength: 100
        isDefault:
          type: boolean
          description: Whether this is the default schedule
          example: false
        timezone:
          type: string
          description: IANA timezone identifier
          example: "America/New_York"
        schedule:
          type: array
          description: Weekly availability schedule
          items:
            $ref: '#/components/schemas/DaySchedule'
          minItems: 7
          maxItems: 7

    DaySchedule:
      type: object
      properties:
        day:
          type: string
          description: Day of the week
          enum: [Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday]
          example: "Monday"
        enabled:
          type: boolean
          description: Whether the user is available on this day
          example: true
        slots:
          type: array
          description: Time slots for this day
          items:
            $ref: '#/components/schemas/TimeSlot'
          example:
            - start: "09:00"
              end: "12:00"
            - start: "13:00"
              end: "17:00"
      required:
        - day
        - enabled
        - slots

    TimeSlot:
      type: object
      properties:
        start:
          type: string
          description: Start time in HH:MM format (24-hour)
          example: "09:00"
          pattern: '^([0-1][0-9]|2[0-3]):[0-5][0-9]$'
        end:
          type: string
          description: End time in HH:MM format (24-hour)
          example: "17:00"
          pattern: '^([0-1][0-9]|2[0-3]):[0-5][0-9]$'
      required:
        - start
        - end

    AvailabilitySchedule:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique schedule identifier
          example: "550e8400-e29b-41d4-a716-446655440000"
        userId:
          type: string
          format: uuid
          description: ID of the user who owns this schedule
          example: "650e8400-e29b-41d4-a716-446655440000"
        name:
          type: string
          description: Schedule name
          example: "Working Hours"
        isDefault:
          type: boolean
          description: Whether this is the default schedule
          example: true
        timezone:
          type: string
          description: IANA timezone identifier
          example: "America/New_York"
        schedule:
          type: array
          description: Weekly availability schedule
          items:
            $ref: '#/components/schemas/DaySchedule'
        eventTypeCount:
          type: integer
          description: Number of event types using this schedule
          example: 3
        createdAt:
          type: string
          format: date-time
          description: Creation timestamp
          example: "2025-01-15T10:30:00Z"
        updatedAt:
          type: string
          format: date-time
          description: Last update timestamp
          example: "2025-01-15T10:30:00Z"
      required:
        - id
        - userId
        - name
        - isDefault
        - timezone
        - schedule
        - createdAt
        - updatedAt

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Error type or code
          example: "NOT_FOUND"
        message:
          type: string
          description: Human-readable error message
          example: "Availability schedule not found"
        statusCode:
          type: integer
          description: HTTP status code
          example: 404
        timestamp:
          type: string
          format: date-time
          description: Error timestamp
          example: "2025-01-15T10:30:00Z"
      required:
        - error
        - message
        - statusCode

    ValidationErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Error type
          example: "VALIDATION_ERROR"
        message:
          type: string
          description: General validation error message
          example: "Validation failed"
        statusCode:
          type: integer
          description: HTTP status code
          example: 422
        errors:
          type: array
          description: Detailed validation errors
          items:
            type: object
            properties:
              field:
                type: string
                description: Field name that failed validation
                example: "schedule[1].slots[0].start"
              message:
                type: string
                description: Validation error message for this field
                example: "Start time must be before end time"
              code:
                type: string
                description: Validation error code
                example: "INVALID_TIME_RANGE"
        timestamp:
          type: string
          format: date-time
          description: Error timestamp
          example: "2025-01-15T10:30:00Z"
      required:
        - error
        - message
        - statusCode
        - errors

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT access token obtained from login

security:
  - bearerAuth: []
